/* 
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.ConfigurationAPI.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.ConfigurationAPI.Model
{
    /// <summary>
    /// Value of a setting
    /// </summary>
    [DataContract]
    public partial class SettingValue :  IEquatable<SettingValue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingValue" /> class.
        /// </summary>
        /// <param name="ConfigSettingValueID">The ID of the setting value.</param>
        /// <param name="ConfigSettingDefinitionID">The ID of the definition of the setting.</param>
        /// <param name="ConfigSettingValue">The value of the setting.</param>
        /// <param name="ConfigSettingLastModified">The last modified date of the setting.</param>
        /// <param name="ConfigSettingName">Name of the setting.</param>
        /// <param name="ConfigSettingDescription">Description of the setting.</param>
        /// <param name="ConfigSettingTags">Setting tags.</param>
        /// <param name="ConfigSettingType">Possible values are: STRING, JSON.</param>
        public SettingValue(string ConfigSettingValueID = default(string), string ConfigSettingDefinitionID = default(string), Object ConfigSettingValue = default(Object), DateTime? ConfigSettingLastModified = default(DateTime?), string ConfigSettingName = default(string), string ConfigSettingDescription = default(string), string ConfigSettingTags = default(string), string ConfigSettingType = default(string))
        {
            this.ConfigSettingValueID = ConfigSettingValueID;
            this.ConfigSettingDefinitionID = ConfigSettingDefinitionID;
            this.ConfigSettingValue = ConfigSettingValue;
            this.ConfigSettingLastModified = ConfigSettingLastModified;
            this.ConfigSettingName = ConfigSettingName;
            this.ConfigSettingDescription = ConfigSettingDescription;
            this.ConfigSettingTags = ConfigSettingTags;
            this.ConfigSettingType = ConfigSettingType;
        }
        
        /// <summary>
        /// The ID of the setting value
        /// </summary>
        /// <value>The ID of the setting value</value>
        [DataMember(Name="ConfigSettingValueID", EmitDefaultValue=false)]
        public string ConfigSettingValueID { get; set; }

        /// <summary>
        /// The ID of the definition of the setting
        /// </summary>
        /// <value>The ID of the definition of the setting</value>
        [DataMember(Name="ConfigSettingDefinitionID", EmitDefaultValue=false)]
        public string ConfigSettingDefinitionID { get; set; }

        /// <summary>
        /// The value of the setting
        /// </summary>
        /// <value>The value of the setting</value>
        [DataMember(Name="ConfigSettingValue", EmitDefaultValue=false)]
        public Object ConfigSettingValue { get; set; }

        /// <summary>
        /// The last modified date of the setting
        /// </summary>
        /// <value>The last modified date of the setting</value>
        [DataMember(Name="ConfigSettingLastModified", EmitDefaultValue=false)]
        public DateTime? ConfigSettingLastModified { get; set; }

        /// <summary>
        /// Name of the setting
        /// </summary>
        /// <value>Name of the setting</value>
        [DataMember(Name="ConfigSettingName", EmitDefaultValue=false)]
        public string ConfigSettingName { get; set; }

        /// <summary>
        /// Description of the setting
        /// </summary>
        /// <value>Description of the setting</value>
        [DataMember(Name="ConfigSettingDescription", EmitDefaultValue=false)]
        public string ConfigSettingDescription { get; set; }

        /// <summary>
        /// Setting tags
        /// </summary>
        /// <value>Setting tags</value>
        [DataMember(Name="ConfigSettingTags", EmitDefaultValue=false)]
        public string ConfigSettingTags { get; set; }

        /// <summary>
        /// Possible values are: STRING, JSON
        /// </summary>
        /// <value>Possible values are: STRING, JSON</value>
        [DataMember(Name="ConfigSettingType", EmitDefaultValue=false)]
        public string ConfigSettingType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SettingValue {\n");
            sb.Append("  ConfigSettingValueID: ").Append(ConfigSettingValueID).Append("\n");
            sb.Append("  ConfigSettingDefinitionID: ").Append(ConfigSettingDefinitionID).Append("\n");
            sb.Append("  ConfigSettingValue: ").Append(ConfigSettingValue).Append("\n");
            sb.Append("  ConfigSettingLastModified: ").Append(ConfigSettingLastModified).Append("\n");
            sb.Append("  ConfigSettingName: ").Append(ConfigSettingName).Append("\n");
            sb.Append("  ConfigSettingDescription: ").Append(ConfigSettingDescription).Append("\n");
            sb.Append("  ConfigSettingTags: ").Append(ConfigSettingTags).Append("\n");
            sb.Append("  ConfigSettingType: ").Append(ConfigSettingType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SettingValue);
        }

        /// <summary>
        /// Returns true if SettingValue instances are equal
        /// </summary>
        /// <param name="input">Instance of SettingValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SettingValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConfigSettingValueID == input.ConfigSettingValueID ||
                    (this.ConfigSettingValueID != null &&
                    this.ConfigSettingValueID.Equals(input.ConfigSettingValueID))
                ) && 
                (
                    this.ConfigSettingDefinitionID == input.ConfigSettingDefinitionID ||
                    (this.ConfigSettingDefinitionID != null &&
                    this.ConfigSettingDefinitionID.Equals(input.ConfigSettingDefinitionID))
                ) && 
                (
                    this.ConfigSettingValue == input.ConfigSettingValue ||
                    (this.ConfigSettingValue != null &&
                    this.ConfigSettingValue.Equals(input.ConfigSettingValue))
                ) && 
                (
                    this.ConfigSettingLastModified == input.ConfigSettingLastModified ||
                    (this.ConfigSettingLastModified != null &&
                    this.ConfigSettingLastModified.Equals(input.ConfigSettingLastModified))
                ) && 
                (
                    this.ConfigSettingName == input.ConfigSettingName ||
                    (this.ConfigSettingName != null &&
                    this.ConfigSettingName.Equals(input.ConfigSettingName))
                ) && 
                (
                    this.ConfigSettingDescription == input.ConfigSettingDescription ||
                    (this.ConfigSettingDescription != null &&
                    this.ConfigSettingDescription.Equals(input.ConfigSettingDescription))
                ) && 
                (
                    this.ConfigSettingTags == input.ConfigSettingTags ||
                    (this.ConfigSettingTags != null &&
                    this.ConfigSettingTags.Equals(input.ConfigSettingTags))
                ) && 
                (
                    this.ConfigSettingType == input.ConfigSettingType ||
                    (this.ConfigSettingType != null &&
                    this.ConfigSettingType.Equals(input.ConfigSettingType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConfigSettingValueID != null)
                    hashCode = hashCode * 59 + this.ConfigSettingValueID.GetHashCode();
                if (this.ConfigSettingDefinitionID != null)
                    hashCode = hashCode * 59 + this.ConfigSettingDefinitionID.GetHashCode();
                if (this.ConfigSettingValue != null)
                    hashCode = hashCode * 59 + this.ConfigSettingValue.GetHashCode();
                if (this.ConfigSettingLastModified != null)
                    hashCode = hashCode * 59 + this.ConfigSettingLastModified.GetHashCode();
                if (this.ConfigSettingName != null)
                    hashCode = hashCode * 59 + this.ConfigSettingName.GetHashCode();
                if (this.ConfigSettingDescription != null)
                    hashCode = hashCode * 59 + this.ConfigSettingDescription.GetHashCode();
                if (this.ConfigSettingTags != null)
                    hashCode = hashCode * 59 + this.ConfigSettingTags.GetHashCode();
                if (this.ConfigSettingType != null)
                    hashCode = hashCode * 59 + this.ConfigSettingType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
